### ISSUE TITLE
Is there planned support for Ubuntu 16.04 ?

### ISSUE THREAD

**Issue by ericoporto** [OpenFOAM/OpenFOAM-dev#3]
Trying to compile from source here, not so much success yet.

**Comment by OpenFOAM** [comment]
We will release packs for Ubuntu 16.04 with the next version of OpenFOAM but in the meantime OpenFOAM-dev should compile on 16.04 and there are people using it on that platform.  Please report any compilation issues on the Mantis bug-reporting system and you will receive the help you need.
